services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"



    localstack:
        image: localstack/localstack
        container_name: localstack_container
        ports:
            - "4566:4566"
            - "4571:4571"


    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq_container
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - "5672:5672"
            - "9090:15672"


    redis:
        image: redis:latest
        container_name: redis_container
        ports:
            - "6379:6379"